module.exports = {
  emojis: ['✨', '🚀', '🤖', '🧠', '☁️', '🔮', '📉', '🧨', '🤡', '🚽', '🪄'],

  todos: [
    'Refactor this to use Blockchain',
    'Ask ChatGPT why this works',
    "Remove this before production (Spoiler: we won't)",
    'Optimized by neural net (approx. accuracy 4%)',
    'This logic came to me in a dream',
    'Co-authored by a hallucinating LLM',
    'TODO: Consult the oracle',
    'Add more layers of abstraction',
    'Rewrite in Rust?',
    'Ensure this is web-scale'
  ],

  logs: [
    'System optimal...',
    'Thinking...',
    'Consulting the cloud...',
    'Downloading more RAM...',
    'Aligning chakras...',
    'Re-calibrating moral compass...',
    'Generating revenue...',
    'Mining crypto in background...'
  ],

  truncations: [
    '... rest of implementation',
    '... remaining logic here',
    '... continue as needed',
    '... implementation details omitted for brevity',
    '... etc',
    '... you get the idea',
    '... similar pattern continues',
    '... handle remaining cases similarly',
    '... add your logic here'
  ],

  jargon: {
    verbs: [
      'Leverage',
      'Synergize',
      'Orchestrate',
      'Architect',
      'Disrupt',
      'Streamline'
    ],
    nouns: [
      'Paradigm',
      'Microservice',
      'Vector',
      'Tensors',
      'Pipeline',
      'Bandwidth'
    ],
    adjectives: [
      'Cloud-native',
      'Serverless',
      'Mission-critical',
      'Robust',
      'Scalable',
      'High-performance'
    ]
  },

  aiDisclaimer:
    '/* 🤖 GENERATED BY CODE-HALLUCINATOR. PROCEED WITH CAUTION. 🤖 */\n'
};
